- name: Configure SSH settings
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
    - { regexp: '^LogLevel', line: 'LogLevel VERBOSE' }
    - { regexp: '^X11Forwarding', line: 'X11Forwarding no' }
    - { regexp: '^PermitTTY', line: 'PermitTTY yes' }
  notify: Restart ssh